import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter, Playfair_Display, Titillium_Web, Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} bg-white`}>
        
        {children}
        </body>
    </html>
  )
}
